# Generated by Django 3.2.3 on 2021-05-20 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_name', models.CharField(max_length=50, verbose_name='团队名称')),
                ('tm_ctime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('tm_utime', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '团队信息',
                'verbose_name_plural': '团队信息',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('user_position', models.CharField(
                    choices=[('TMR', '销售'), ('TMS', '销售主管'), ('CCM', '销售经理'), ('TM', '项目负责人'), ('AD', '行政'),
                             ('QA', '质检'), ('DH', '跟单'), ('PL', '企划'), ('TR', '培训'), ('RE', '招聘')], default='TMR',
                    max_length=30, verbose_name='职务')),
                ('user_workplace', models.CharField(max_length=50, verbose_name='职场')),
                ('user_doamin', models.CharField(max_length=50, verbose_name='域账号')),
                ('user_phone', models.CharField(max_length=50, verbose_name='工作手机')),
                ('user_department', models.CharField(max_length=50, verbose_name='部门')),
                ('user_pid', models.CharField(blank=True, max_length=100, null=True, verbose_name='员工工号')),
                ('user_area',
                 models.CharField(choices=[('N', '网电北区'), ('S', '网电南区'), ('E', '网电东区'), ('W', '网电北区'), ('C', '网电中区')],
                     default='N', max_length=50, verbose_name='所在区域')),
                ('user_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='员工邮箱')),
                ('user_status', models.SmallIntegerField(choices=[(0, '在职'), (1, '离职')], default=0, verbose_name='状态')),
                ('user_ctime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('user_utime', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('user_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                    to='users.team')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
            },
        ),
    ]
