# Generated by Django 3.2.3 on 2021-05-20 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp_name', models.CharField(max_length=50, verbose_name='部门名称')),
                ('dp_ctime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('dp_utime', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '部门信息',
                'verbose_name_plural': '部门信息',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='tm_department',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_position',
            field=models.CharField(
                choices=[('AD', '行政'), ('QA', '质检'), ('DH', '跟单'), ('TR', '培训'), ('RE', '招聘'), ('TMR', '销售'),
                         ('TMS', '销售主管'), ('CCM', '销售经理'), ('TM', '项目负责人')], default='TMR', max_length=30,
                verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.team',
                verbose_name='所在团队'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_department',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE,
                to='users.department', verbose_name='部门'),
        ),
    ]
