# Generated by Django 3.2.3 on 2021-05-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20210520_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tm_ctime',
            field=models.DateField(auto_now_add=True, db_column='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tm_department',
            field=models.CharField(db_column='所属部门', max_length=50, verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tm_name',
            field=models.CharField(db_column='团队名称', max_length=50, verbose_name='团队名称'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tm_utime',
            field=models.DateField(auto_now=True, db_column='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_area',
            field=models.CharField(choices=[('N', '网电西区'), ('S', '网电南区'), ('E', '网电东区'), ('W', '网电北区'), ('C', '网电中区')],
                default='N', max_length=50, verbose_name='所在区域'),
        ),
    ]
