# Generated by Django 3.2.3 on 2021-05-21 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20210520_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_province', models.CharField(max_length=50, verbose_name='省份')),
                ('ad_city', models.CharField(max_length=50, verbose_name='城市')),
                ('ad_ctime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('ad_utime', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '地区信息',
                'verbose_name_plural': '地区信息',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_name', models.CharField(max_length=50, verbose_name='职位名称')),
                ('po_ctime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('po_utime', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '职位信息',
                'verbose_name_plural': '职位信息',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_area',
        ),
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                to='users.address', verbose_name='所在区域'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_position',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE,
                to='users.position', verbose_name='职务'),
        ),
    ]
