# Generated by Django 3.2.3 on 2021-05-21 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_auto_20210521_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tm_department',
        ),
    ]
