# Generated by Django 3.2.3 on 2021-05-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_remove_team_tm_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ad_city',
            field=models.CharField(max_length=100, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='address',
            name='ad_province',
            field=models.CharField(max_length=100, verbose_name='省份'),
        ),
    ]
