# Generated by Django 3.2.3 on 2021-05-20 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20210520_1448'),
        ('assets', '0002_auto_20210520_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='com_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                to='users.user', verbose_name='使用人'),
        ),
    ]
