# Generated by Django 3.2.3 on 2021-05-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0003_alter_sipphone_sip_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipphone',
            name='sip_confirmed_date',
            field=models.DateField(max_length=50, null=True, verbose_name='过保日期'),
        ),
        migrations.AlterField(
            model_name='sipphone',
            name='sip_manufacturer',
            field=models.CharField(blank=True, default='联地科技', max_length=200, null=True, verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='sipphone',
            name='sip_product_date',
            field=models.DateField(default='2020/6/15', max_length=50, null=True, verbose_name='出厂日期'),
        ),
    ]
