# Generated by Django 3.2.3 on 2021-05-20 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20210520_1448'),
        ('assets', '0004_auto_20210520_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='com_confirmed_date',
            field=models.DateField(max_length=50, verbose_name='过保日期'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='com_ctime',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='com_department',
            field=models.CharField(max_length=50, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='com_mac',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MAC地址'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='com_manufacturer',
            field=models.CharField(blank=True, default='联想', max_length=50, null=True, verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='com_model',
            field=models.CharField(max_length=50, verbose_name='电脑型号'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='com_name',
            field=models.CharField(max_length=50, verbose_name='计算机名'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='com_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                to='users.user', verbose_name='使用人'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='com_product_date',
            field=models.DateField(max_length=50, verbose_name='出厂日期'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='com_sn',
            field=models.CharField(max_length=50, null=True, verbose_name='SN号'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='com_status',
            field=models.SmallIntegerField(choices=[(0, '使用'), (1, '闲置'), (2, '库存'), (3, '故障'), (4, '返修')], default=0,
                verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='com_tag',
            field=models.CharField(max_length=50, verbose_name='资产标签'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='com_type',
            field=models.SmallIntegerField(choices=[(0, '台式机'), (1, '笔记本')], default=0, verbose_name='电脑类型'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='com_utime',
            field=models.DateField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='com_workplace',
            field=models.CharField(max_length=50, verbose_name='职场'),
        ),
    ]
