# Generated by Django 3.2.3 on 2021-05-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assets', '0004_auto_20210519_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='com_ctime',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='com_utime',
            field=models.DateField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='headset',
            name='hd_ctime',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='headset',
            name='hd_utime',
            field=models.DateField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='sipphone',
            name='sip_ctime',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sipphone',
            name='sip_utime',
            field=models.DateField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
