# Generated by Django 3.2.3 on 2021-05-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tl_title', models.CharField(max_length=100, verbose_name='标题')),
                ('tl_text', models.CharField(max_length=200, verbose_name='记录')),
                ('tl_status', models.CharField(choices=[(0, '已完成'), (1, '待完成')], max_length=200, verbose_name='进度')),
                ('tl_ctime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('tl_utime', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '待办事项',
                'verbose_name_plural': '待办事项',
            },
        ),
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_title', models.CharField(max_length=100, verbose_name='标题')),
                ('up_text', models.CharField(max_length=200, verbose_name='记录')),
                ('up_ctime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('up_utime', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '更新记录',
                'verbose_name_plural': '更新记录',
            },
        ),
    ]
